name: Generate GitHub Profile Summary Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: Sriram-Mullapudi
          UTC_OFFSET: -4
